/* ============================================================================
   §9 sound design — every sample generated by the code in this file.

   WHERE THE SOUNDS COME FROM, because it matters and the repo is public.
   Nothing here is sampled, downloaded, or derived from a library. Each cue is
   synthesised from oscillators and filtered noise by the functions below, so
   the audio inherits the repository's licence and there is no third-party
   right in it to get wrong. There is no `assets/sfx` directory and there is
   deliberately no way to add one without this comment being edited.

   WHY IT IS PURE DSP OVER Float32Array rather than a Web Audio node graph.
   Three reasons, in order of how much they mattered:

     1. It is TESTABLE. A node graph can only be exercised in a browser, so in
        practice it is never asserted on at all — §13.7's recurring bug is a
        check that cannot fail, and "the sound code did not throw" is one.
        These are pure functions, so `sound-design.test.ts` renders every cue in
        Node and asserts real properties: finite, within range, non-silent, the
        right length, the pass ladder genuinely ascending, the clutch loop
        genuinely seamless.
     2. It is DETERMINISTIC. The noise source is a seeded PRNG, so a cue renders
        identically every time and a test can assert an exact peak.
     3. It is what a preloaded buffer pool wants anyway. §9 asks for a pool, not
        a graph rebuilt per shot: these render once into `AudioBuffer`s and each
        play is one `BufferSource`.

   Everything is band-limited by construction — additive partials rather than a
   hard square or saw — because an aliased edge is the difference between a
   sound that reads as designed and one that reads as a beep.
   ========================================================================= */

const TAU = Math.PI * 2;

/** One semitone. The §9 pass ladder is built on this. */
export const SEMITONE = 2 ** (1 / 12);

/**
 * The pass ladder's height, in semitones.
 *
 * §6.4 segments the test bar into one cell per test up to `MAX_CELLS` (20), so
 * a sweep can be twenty ticks long. The placeholder capped its rise at 14,
 * which meant the last six ticks of the longest sweep were identical — the run
 * flattening exactly where it is most impressive. It spans the full 20.
 */
export const PASS_STEPS = 20;

/** Deterministic white noise in [-1, 1). xorshift32 — no allocation, no Math.random. */
function rng(seed: number): () => number {
  let s = seed >>> 0 || 1;
  return () => {
    s ^= s << 13;
    s >>>= 0;
    s ^= s >>> 17;
    s ^= s << 5;
    s >>>= 0;
    return (s / 0x100000000) * 2 - 1;
  };
}

/**
 * Percussive envelope: fast linear attack, then a shaped decay.
 *
 * `curve` above 1 decays faster at the start, which is what makes a hit read as
 * a hit. Returns 0 outside [0, dur].
 */
function envelope(t: number, dur: number, attack: number, curve: number): number {
  if (t < 0 || t > dur) return 0;
  if (t < attack) return t / attack;
  const x = (t - attack) / Math.max(1e-6, dur - attack);
  return (1 - x) ** curve;
}

interface ToneOpts {
  /** Seconds from the start of the buffer. */
  at?: number;
  dur: number;
  /** Starting frequency, Hz. */
  f0: number;
  /** Exponential glide target. Omit to hold `f0`. */
  f1?: number;
  gain?: number;
  /**
   * Relative amplitudes of the harmonic series, index 0 being the fundamental.
   * Additive rather than a named waveshape, so nothing aliases.
   */
  partials?: number[];
  attack?: number;
  curve?: number;
  /**
   * Frequency modulation, which is what gives a tick a metallic attack that
   * settles into a pure tone. `index` is in units of the carrier frequency and
   * decays with its own time constant.
   */
  fm?: { ratio: number; index: number; decay: number };
}

/** Adds an enveloped, band-limited tone into `out`. */
function tone(out: Float32Array, sr: number, o: ToneOpts): void {
  const {
    at = 0,
    dur,
    f0,
    f1,
    gain = 0.5,
    partials = [1],
    attack = 0.004,
    curve = 2.4,
    fm,
  } = o;
  const start = Math.round(at * sr);
  const n = Math.round(dur * sr);
  const nyquist = sr / 2;

  /* Phase is accumulated rather than computed from `sin(TAU*f*t)` so that a
     glide stays continuous — recomputing from absolute time makes a swept
     oscillator jump. */
  const phase = new Float64Array(partials.length);
  let fmPhase = 0;

  for (let i = 0; i < n; i++) {
    const j = start + i;
    if (j < 0 || j >= out.length) continue;
    const t = i / sr;
    const frac = t / dur;
    const f = f1 === undefined ? f0 : f0 * (f1 / f0) ** frac;

    let mod = 0;
    if (fm) {
      fmPhase += (TAU * f * fm.ratio) / sr;
      mod = Math.sin(fmPhase) * fm.index * f * Math.exp(-t / fm.decay);
    }

    const amp = envelope(t, dur, attack, curve) * gain;
    let sample = 0;
    for (let p = 0; p < partials.length; p++) {
      const pf = f * (p + 1) + mod;
      /* Above Nyquist a partial folds back and rings as an inharmonic whistle,
         so it is dropped rather than allowed to alias. */
      if (pf >= nyquist || pf <= 0) continue;
      phase[p]! += (TAU * pf) / sr;
      sample += Math.sin(phase[p]!) * partials[p]!;
    }
    out[j]! += sample * amp;
  }
}

interface NoiseOpts {
  at?: number;
  dur: number;
  gain?: number;
  /** Filter cutoff at the start, Hz. */
  f0: number;
  /** Exponential cutoff sweep target. */
  f1?: number;
  q?: number;
  mode?: "low" | "band" | "high";
  attack?: number;
  curve?: number;
  seed?: number;
}

/**
 * Adds filtered noise into `out`, via a Chamberlin state-variable filter so the
 * cutoff can sweep per sample — that sweep is what makes a whoosh a whoosh
 * rather than a hiss.
 */
function noise(out: Float32Array, sr: number, o: NoiseOpts): void {
  const {
    at = 0,
    dur,
    gain = 0.5,
    f0,
    f1,
    q = 1.1,
    mode = "band",
    attack = 0.004,
    curve = 2.2,
    seed = 0x5eed,
  } = o;
  const start = Math.round(at * sr);
  const n = Math.round(dur * sr);
  const next = rng(seed);
  const damp = 1 / q;
  let low = 0;
  let band = 0;

  for (let i = 0; i < n; i++) {
    const j = start + i;
    const t = i / sr;
    const frac = t / dur;
    const fc = f1 === undefined ? f0 : f0 * (f1 / f0) ** frac;
    /* The SVF is only stable while f < ~sr/3; clamping keeps a steep sweep from
       blowing up into a burst of full-scale noise. */
    const f = Math.min(1.4, 2 * Math.sin((Math.PI * Math.min(fc, sr / 3)) / sr));

    const input = next();
    const high = input - low - damp * band;
    band += f * high;
    low += f * band;

    if (j < 0 || j >= out.length) continue;
    const picked = mode === "low" ? low : mode === "high" ? high : band;
    out[j]! += picked * envelope(t, dur, attack, curve) * gain;
  }
}

/**
 * A small Schroeder reverb, rendered in place.
 *
 * Four combs into two allpasses. It is not a convolution and it is not trying
 * to be a room — it is the difference between a cue that sounds recorded and
 * one that sounds like a function call, and it is thirty lines with no assets.
 */
function reverb(buf: Float32Array, sr: number, mix: number, decay: number): void {
  const combDelays = [0.0297, 0.0371, 0.0411, 0.0437];
  const allpassDelays = [0.005, 0.0017];
  const wet = new Float32Array(buf.length);

  for (const d of combDelays) {
    const len = Math.max(1, Math.round(d * sr));
    const line = new Float32Array(len);
    /* Feedback set from the delay length so every comb decays over the same
       wall time; a fixed feedback makes short combs die first and the tail
       shift in colour as it fades. */
    const fb = 10 ** ((-3 * d) / decay);
    let idx = 0;
    for (let i = 0; i < buf.length; i++) {
      const out = line[idx]!;
      line[idx] = buf[i]! + out * fb;
      idx = (idx + 1) % len;
      wet[i]! += out * 0.25;
    }
  }

  for (const d of allpassDelays) {
    const len = Math.max(1, Math.round(d * sr));
    const line = new Float32Array(len);
    const g = 0.5;
    let idx = 0;
    for (let i = 0; i < wet.length; i++) {
      const delayed = line[idx]!;
      const out = -g * wet[i]! + delayed;
      line[idx] = wet[i]! + g * out;
      idx = (idx + 1) % len;
      wet[i] = out;
    }
  }

  for (let i = 0; i < buf.length; i++) buf[i] = buf[i]! * (1 - mix) + wet[i]! * mix;
}

/**
 * Soft-clips and normalises to `peak`.
 *
 * `tanh` rather than a hard clamp because a hard clamp on a loud transient is
 * an audible crackle, and every one of these cues fires at the moment the
 * player is paying most attention.
 */
function finish(buf: Float32Array, peak = 0.9): void {
  let max = 0;
  for (let i = 0; i < buf.length; i++) {
    buf[i] = Math.tanh(buf[i]!);
    const a = Math.abs(buf[i]!);
    if (a > max) max = a;
  }
  if (max < 1e-6) return;
  const k = peak / max;
  for (let i = 0; i < buf.length; i++) buf[i]! *= k;
}

/** Fades the first and last few milliseconds so a buffer never starts or ends on a step. */
function deClick(buf: Float32Array, sr: number, ms = 3): void {
  const n = Math.min(Math.round((ms / 1000) * sr), Math.floor(buf.length / 2));
  for (let i = 0; i < n; i++) {
    const g = i / n;
    buf[i]! *= g;
    buf[buf.length - 1 - i]! *= g;
  }
}

/* --- The cues -------------------------------------------------------------
   Durations are stated in `CUE_SECONDS` and asserted against §5's timings by
   the test, because §6.3, §6.6 and §6.7 are rhythms and a cue that outlasts its
   slot smears the rhythm it was written for. */

export type CueName =
  | "queue_pop"
  | "countdown_tick"
  | "countdown_final"
  | "test_pass"
  | "test_fail"
  | "submit"
  | "compile"
  | "victory"
  | "defeat"
  | "rank_up"
  | "emote"
  | "clutch_ambient";

export const CUE_SECONDS: Record<CueName, number> = {
  queue_pop: 0.9,
  countdown_tick: 0.13,
  countdown_final: 0.5,
  test_pass: 0.16,
  test_fail: 0.32,
  submit: 0.46,
  compile: 0.34,
  victory: 2.4,
  defeat: 1.35,
  rank_up: 1.9,
  emote: 0.14,
  clutch_ambient: 1.8,
};

/** §9's queue pop — a low impact. The §6.2 nameplate collision lands on this. */
function queuePop(sr: number): Float32Array {
  const buf = new Float32Array(Math.round(CUE_SECONDS.queue_pop * sr));
  // The body: a kick whose pitch collapses, which is what reads as weight.
  tone(buf, sr, { dur: 0.34, f0: 150, f1: 42, gain: 0.95, curve: 2.6, attack: 0.001 });
  // The transient that makes it audible on a laptop speaker with no bass.
  noise(buf, sr, { dur: 0.09, f0: 2600, f1: 380, gain: 0.4, q: 0.8, curve: 3.4, seed: 11 });
  // A sub tail under it, so it has size on headphones.
  tone(buf, sr, { dur: 0.7, f0: 58, f1: 40, gain: 0.5, curve: 1.6, attack: 0.006 });
  // A metallic ring, low in the mix — the "impact hit" of §6.2 step 3.
  tone(buf, sr, {
    at: 0.002,
    dur: 0.5,
    f0: 210,
    gain: 0.18,
    curve: 3,
    fm: { ratio: 2.71, index: 3.4, decay: 0.06 },
  });
  reverb(buf, sr, 0.16, 0.5);
  finish(buf);
  deClick(buf, sr);
  return buf;
}

/**
 * §6.3's countdown beat — deliberately DRY.
 *
 * No reverb and a hard 130ms envelope, because a countdown is a rhythm and a
 * tail smears the grid it defines. It is the one place where a less impressive
 * sound is the better one.
 */
function countdownTick(sr: number, final: boolean): Float32Array {
  const dur = final ? CUE_SECONDS.countdown_final : CUE_SECONDS.countdown_tick;
  const buf = new Float32Array(Math.round(dur * sr));
  const f = final ? 990 : 660; // §6.3: the final beat is pitched higher — a fifth up.
  tone(buf, sr, {
    dur: final ? 0.4 : 0.1,
    f0: f,
    gain: 0.6,
    partials: [1, 0.32, 0.12],
    curve: final ? 2.2 : 3.6,
    attack: 0.001,
  });
  noise(buf, sr, { dur: 0.02, f0: 4200, gain: 0.25, q: 0.7, curve: 4, seed: 23 });
  if (final) {
    /* THE GO BEAT GETS BODY WITHOUT GETTING LOWER, and that distinction was a
       real bug: a 330Hz body under the 990Hz lead made the final beat measure
       331Hz — a FIFTH BELOW the 660Hz regular tick, when §6.3 requires it
       pitched higher. It sounded bigger and read as lower, which is the exact
       opposite of what the beat is for. Weight now comes from a sub an octave
       and a half down, which is heard as force rather than as pitch, and from
       an OCTAVE above the lead.

       The octave is not arbitrary either. A fifth above (1485Hz) was tried and
       measured 495Hz, still below the 660Hz tick — because 990 and 1485 share
       a sub-multiple and the ear supplies the missing fundamental an octave
       down. Any harmonically related pair implies a lower root, so the only
       safe reinforcement of a pitch is its own octaves. */
    tone(buf, sr, { dur: 0.42, f0: 1980, gain: 0.22, curve: 2.6, attack: 0.002 });
    tone(buf, sr, { dur: 0.3, f0: 110, f1: 82, gain: 0.45, curve: 2 });
    reverb(buf, sr, 0.12, 0.4);
  }
  finish(buf, final ? 0.92 : 0.72);
  deClick(buf, sr, 2);
  return buf;
}

/**
 * §9's test tick, at `step` semitones above the root.
 *
 * FM with a fast-decaying index gives a struck-metal attack that settles into a
 * clean tone — bell-like rather than beep-like, and short enough that twenty of
 * them at §5's `dur.reveal` cadence read as a run instead of a smear.
 */
function testPass(sr: number, step: number): Float32Array {
  const buf = new Float32Array(Math.round(CUE_SECONDS.test_pass * sr));
  const f = 440 * SEMITONE ** step;
  tone(buf, sr, {
    dur: 0.155,
    f0: f,
    gain: 0.55,
    partials: [1, 0.28, 0.1],
    curve: 3.2,
    attack: 0.0015,
    fm: { ratio: 3.5, index: 1.2, decay: 0.014 },
  });
  // An octave above at low level, which reads as brightness rather than as a note.
  tone(buf, sr, { dur: 0.09, f0: f * 2, gain: 0.14, curve: 4, attack: 0.001 });
  finish(buf, 0.78);
  deClick(buf, sr, 2);
  return buf;
}

/** §9's dull thud. Low, fast, no shine — and it must not sound like a pass. */
function testFail(sr: number): Float32Array {
  const buf = new Float32Array(Math.round(CUE_SECONDS.test_fail * sr));
  tone(buf, sr, { dur: 0.3, f0: 165, f1: 68, gain: 0.85, curve: 2.2, attack: 0.002 });
  noise(buf, sr, { dur: 0.11, f0: 700, f1: 130, gain: 0.35, q: 1.4, mode: "low", curve: 2.6, seed: 71 });
  // A slightly detuned second body, which is what makes it read as dull rather
  // than as a clean low note.
  tone(buf, sr, { dur: 0.22, f0: 158, f1: 74, gain: 0.3, curve: 2.6 });
  finish(buf, 0.85);
  deClick(buf, sr);
  return buf;
}

/** §9's submit whoosh — §6.6 step 1, the moment it leaves your hands. */
function submit(sr: number): Float32Array {
  const buf = new Float32Array(Math.round(CUE_SECONDS.submit * sr));
  noise(buf, sr, {
    dur: 0.42,
    f0: 260,
    f1: 4200,
    gain: 0.6,
    q: 1.6,
    curve: 1.2,
    attack: 0.05,
    seed: 907,
  });
  // A rising tone inside the noise gives it a direction the noise alone lacks.
  tone(buf, sr, { dur: 0.4, f0: 180, f1: 720, gain: 0.16, curve: 1.1, attack: 0.06 });
  reverb(buf, sr, 0.2, 0.45);
  finish(buf, 0.7);
  deClick(buf, sr);
  return buf;
}

/** §6.5's compile pulse. Quiet by design — it fires often and is peripheral. */
function compile(sr: number): Float32Array {
  const buf = new Float32Array(Math.round(CUE_SECONDS.compile * sr));
  noise(buf, sr, { dur: 0.3, f0: 900, f1: 2200, gain: 0.3, q: 2.4, curve: 1.8, attack: 0.03, seed: 313 });
  tone(buf, sr, { dur: 0.26, f0: 300, f1: 460, gain: 0.16, curve: 2, attack: 0.02 });
  finish(buf, 0.42);
  deClick(buf, sr);
  return buf;
}

/**
 * §6.7's victory sting — a rising major arpeggio over a swell.
 *
 * Fits inside `dur.victory`'s mandatory 2800ms. It is longer than `dur.skip`'s
 * 700ms on purpose and the engine fades it rather than cutting it; see the note
 * on `release` in sound.ts.
 */
function victory(sr: number): Float32Array {
  const buf = new Float32Array(Math.round(CUE_SECONDS.victory * sr));
  const root = 261.63; // C4
  const arp = [0, 4, 7, 12, 16, 19]; // major triad across two octaves
  arp.forEach((semi, i) => {
    const f = root * SEMITONE ** semi;
    tone(buf, sr, {
      at: 0.06 * i,
      dur: 1.5 - 0.1 * i,
      f0: f,
      gain: 0.38 - 0.02 * i,
      partials: [1, 0.4, 0.16, 0.06],
      curve: 2.1,
      attack: 0.006,
    });
  });
  // The swell underneath, which is what makes it a sting and not a doorbell.
  tone(buf, sr, { at: 0.02, dur: 1.9, f0: root / 2, gain: 0.34, partials: [1, 0.3], curve: 1.4, attack: 0.09 });
  // A bright hit at the top of the rise, landing with the §6.7 particle burst.
  tone(buf, sr, {
    at: 0.34,
    dur: 1.5,
    f0: root * 4,
    gain: 0.26,
    curve: 2.6,
    attack: 0.002,
    fm: { ratio: 2.4, index: 2.2, decay: 0.05 },
  });
  noise(buf, sr, { at: 0.33, dur: 0.5, f0: 3000, f1: 7000, gain: 0.16, q: 0.9, curve: 2, seed: 5150 });
  reverb(buf, sr, 0.3, 1.5);
  finish(buf, 0.92);
  deClick(buf, sr, 5);
  return buf;
}

/**
 * §6.7's defeat — falling, and SHORTER.
 *
 * §5 makes `dur.defeat` deliberately shorter than `dur.victory` because losing
 * should sting once and get out of the way. The sound follows the same rule: it
 * is dark, it descends, and it does not linger.
 */
function defeat(sr: number): Float32Array {
  const buf = new Float32Array(Math.round(CUE_SECONDS.defeat * sr));
  const root = 220;
  [0, -3, -8].forEach((semi, i) => {
    tone(buf, sr, {
      at: 0.09 * i,
      dur: 0.95 - 0.15 * i,
      f0: root * SEMITONE ** semi,
      gain: 0.34,
      partials: [1, 0.22, 0.08],
      curve: 1.9,
      attack: 0.01,
    });
  });
  tone(buf, sr, { at: 0.05, dur: 1.1, f0: 110, f1: 72, gain: 0.42, partials: [1, 0.2], curve: 1.5, attack: 0.03 });
  reverb(buf, sr, 0.22, 0.9);
  finish(buf, 0.75);
  deClick(buf, sr, 5);
  return buf;
}

/** §9's rank-up chord, under §6.7's badge assembling from fragments. */
function rankUp(sr: number): Float32Array {
  const buf = new Float32Array(Math.round(CUE_SECONDS.rank_up * sr));
  const root = 196; // G3
  for (const semi of [0, 7, 12, 16, 19, 24]) {
    const f = root * SEMITONE ** semi;
    // Two voices a few cents apart. The beating between them is what makes a
    // synthesised chord sound wide instead of sterile.
    tone(buf, sr, { dur: 1.7, f0: f, gain: 0.2, partials: [1, 0.36, 0.14, 0.05], curve: 1.3, attack: 0.02 });
    tone(buf, sr, { dur: 1.7, f0: f * 1.004, gain: 0.16, partials: [1, 0.3, 0.1], curve: 1.3, attack: 0.03 });
  }
  noise(buf, sr, { dur: 0.9, f0: 1800, f1: 9000, gain: 0.14, q: 0.8, curve: 1.5, attack: 0.12, seed: 8181 });
  tone(buf, sr, { dur: 1.2, f0: 98, gain: 0.3, partials: [1, 0.25], curve: 1.3, attack: 0.02 });
  reverb(buf, sr, 0.34, 1.8);
  finish(buf, 0.86);
  deClick(buf, sr, 6);
  return buf;
}

/** §9's soft pop. Rate-limited to one per 15s, so it can afford to be pleasant. */
function emote(sr: number): Float32Array {
  const buf = new Float32Array(Math.round(CUE_SECONDS.emote * sr));
  tone(buf, sr, { dur: 0.11, f0: 520, f1: 880, gain: 0.5, curve: 3.4, attack: 0.002 });
  tone(buf, sr, { dur: 0.05, f0: 1760, gain: 0.1, curve: 4, attack: 0.001 });
  finish(buf, 0.55);
  deClick(buf, sr, 2);
  return buf;
}

/**
 * §6.5's clutch ambient — a sub-bass loop that fades in above 80%.
 *
 * IT MUST LOOP SEAMLESSLY, which constrains the maths rather than the taste:
 * the buffer holds a whole number of cycles of every component, so the last
 * sample joins the first without a step. The 1.8s length is §6.5's breathing
 * cycle, so the sound and the viewport-edge glow breathe together rather than
 * drifting in and out of phase over a match.
 */
function clutchAmbient(sr: number): Float32Array {
  const dur = CUE_SECONDS.clutch_ambient;
  const n = Math.round(dur * sr);
  const buf = new Float32Array(n);
  // Frequencies chosen so f*dur is an integer: one cycle boundary at the seam.
  const partials: [number, number][] = [
    [50, 0.55], // 90 cycles in 1.8s
    [75, 0.22], // 135
    [100, 0.12], // 180
  ];
  for (let i = 0; i < n; i++) {
    const t = i / sr;
    // One full LFO cycle across the buffer, so the amplitude also joins up.
    const breath = 0.55 + 0.45 * (0.5 - 0.5 * Math.cos((TAU * i) / n));
    let s = 0;
    for (const [f, a] of partials) s += Math.sin(TAU * f * t) * a;
    buf[i] = s * breath * 0.5;
  }
  // No de-click and no reverb: both would break the seam this is built around.
  finish(buf, 0.55);
  return buf;
}

/**
 * Renders one cue. `step` selects a rung of the `test_pass` ladder.
 *
 * Pure and deterministic — same arguments, same samples, every time.
 */
export function renderCue(cue: CueName, sr: number, step = 0): Float32Array {
  switch (cue) {
    case "queue_pop":
      return queuePop(sr);
    case "countdown_tick":
      return countdownTick(sr, false);
    case "countdown_final":
      return countdownTick(sr, true);
    case "test_pass":
      return testPass(sr, step);
    case "test_fail":
      return testFail(sr);
    case "submit":
      return submit(sr);
    case "compile":
      return compile(sr);
    case "victory":
      return victory(sr);
    case "defeat":
      return defeat(sr);
    case "rank_up":
      return rankUp(sr);
    case "emote":
      return emote(sr);
    case "clutch_ambient":
      return clutchAmbient(sr);
  }
}

export const CUE_NAMES = Object.keys(CUE_SECONDS) as CueName[];
