export {
  JUDGE_QUEUE_KEY,
  JudgeEventSchema,
  JudgeJobSchema,
  JudgeTestSchema,
  LanguageSchema,
  VerdictSchema,
  judgeChannel,
  type JudgeEvent,
  type JudgeJob,
  type JudgeTest,
  type Language,
  type Verdict,
  // Explicit .ts extension: apps/judge runs under bare Node ESM, which does not
  // do extensionless resolution the way a bundler does. Without it the worker
  // dies at startup with ERR_MODULE_NOT_FOUND.
} from "./judge.ts";

export {
  AcceptProgressSchema,
  ClockSchema,
  CodeSubmitSchema,
  EditorChangeSchema,
  EditorDeltaOutSchema,
  EditorDeltaSchema,
  EditorDesyncSchema,
  EditorOriginSchema,
  EditorResyncSchema,
  EditorSnapshotOutSchema,
  EditorSnapshotSchema,
  JudgingHoldSchema,
  MAX_SOURCE_BYTES,
  OpponentPulseSchema,
  OpponentStatusSchema,
  PulseReportSchema,
  RatingDeltaSchema,
  SpectateEndedSchema,
  SpectateReadySchema,
  SpectateWatchSchema,
  SubmissionAckSchema,
  SubmissionVerdictSchema,
  TestResultSchema,
  VerdictNameSchema,
  CountdownSchema,
  ErrorSchema,
  LOG_EVENT_TYPES,
  MatchAcceptSchema,
  MatchEndSchema,
  MatchFoundSchema,
  MatchResyncSchema,
  MatchStartSchema,
  MatchStateSchema,
  OpponentPresenceSchema,
  PlayerCardSchema,
  QueueJoinSchema,
  QueueLeaveSchema,
  QueueStatusSchema,
  SideSchema,
  type ClientToServer,
  type LogEventType,
  type EditorChange,
  type EditorDelta,
  type EditorOrigin,
  type MatchOutcomeWire,
  type RatingDelta,
  type VerdictName,
  type PlayerCard,
  type ServerToClient,
  type Side,
} from "./events.ts";
